In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[0:5] = 100

In [8]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr = np.arange(0,11)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
slice_of_arr = arr[0:6]

In [12]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [13]:
slice_of_arr[:] = 99

In [14]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [15]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
arr_copy = arr.copy()

In [17]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [19]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [20]:
arr_2d[1]

array([20, 25, 30])

In [21]:
arr_2d[0]

array([ 5, 10, 15])

In [22]:
arr_copy2 = arr[:]

In [23]:
arr_copy2

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
arr_copy2[0] = arr_copy2[0]+1

In [25]:
arr_copy2

array([100,  99,  99,  99,  99,  99,   6,   7,   8,   9,  10])

In [26]:
arr

array([100,  99,  99,  99,  99,  99,   6,   7,   8,   9,  10])

In [27]:
arr_2d[2]

array([35, 40, 45])

In [28]:
arr2d = np.zeros((10,10))

In [29]:
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [30]:
arr_length = arr2d.shape[1]
arr_length

10

In [31]:
arr_height = arr2d.shape[0]
arr_height

10

In [32]:
arr_height = arr2d.shape[2]
arr_height

IndexError: tuple index out of range